# Generated by Django 6.0.4 on 2026-04-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termcontent',
            name='youtube_id',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
